[tracker] Start automatically. Add setting to start/stop it.
paparazzi/paparazzi pull request #2640
Opened 2021-01-06 14:24 UTC by Fabien-B

Tracker start sending data automatically while the drone is in flight.
Also add a setting to start sending data when the drone is not in flight.

2021-01-06 15:38 UTC, gautierhattenberger requested changes

2021-01-06 15:38 UTC, gautierhattenberger commented on sw/airborne/modules/e_identification_fr/e_identification_fr.c
> +  if(autopilot_in_flight()) {
`autopilot_in_flight` is currently only working on rotorcraft, but fixedwing can use `launch` variable instead (use ifdef `FIXEDWING_FIRMWARE` or `ROTORCRAFT_FIRMWARE`)
see #2641

2021-01-06 15:38 UTC, gautierhattenberger commented on conf/modules/e_identification_fr.xml
> +        <dl_setting shortname="e_id_running" var="e_identification_started" min="0" step="1" max="1"/>
add `values="STOPPED|RUNNING` attribute ?

2021-01-06 15:38 UTC, gautierhattenberger commented on sw/airborne/modules/e_identification_fr/e_identification_fr.c
> +    e_identification_started = true;
so no way to stop in flight ? might be better like that I guess

2021-01-07 18:45 UTC, OpenUAS commented
A function to start or stop which is callable in a flightplan welcomed

2021-01-11 08:43 UTC, gautierhattenberger approved these changes

2021-01-11 08:45 UTC, gautierhattenberger commented
> A function to start or stop which is callable in a flightplan welcomed

This is possible by changing the running state of the module periodic function. As this is a legal requirement, I don't want to make it "too" easy.

2021-01-11 08:45 UTC, merged