Fix MPU6000 spikes in certain chipbatches
paparazzi/paparazzi pull request #2759
Opened 2021-08-10 13:04 UTC by OpenUAS

On certain Flight-controller, either bad batch of MPU6000, overheat, Non clean power and whatnot max value spikes can occur. This completely messes up the IMU attitude state. those boards are unique, to expensive or not feasible to replace chip.To still be able to fly these flight-controllers an 3value median filter is added to the RAW output. Default MPU module behaviour is still the same but by adding` <define name="IMU_MPU_USE_MEDIAN_FILTER" value="TRUE"/>` to the mpu6000 module in airframe the issue is resolved with this fix, see screenshot of before and after... BTW mind the Scale, no it is not more noise... ;-)

### **Before**
![BeforeFix](https://user-images.githubusercontent.com/483944/128871438-3dfb38df-6464-4b26-b176-efc45b703c6f.png)

### **After**
![AfterFix](https://user-images.githubusercontent.com/483944/128871480-9edd49bd-9f8c-471b-8505-7d872ffd96b2.png)

2021-08-10 13:05 UTC, OpenUAS commented
BTW the airframe was added to be able to validate and testfly the fix.

2021-08-10 14:44 UTC, gautierhattenberger requested changes

2021-08-10 14:44 UTC, gautierhattenberger commented on sw/airborne/subsystems/imu/imu_mpu6000.c
> +#ifdef IMU_MPU_USE_MEDIAN_FILTER
please replace the `#ifdef` by `#if` in this case, same for the other occurrences

2021-08-10 14:44 UTC, gautierhattenberger commented on sw/airborne/subsystems/imu/imu_mpu6000.c
> +struct MedianFilter3Int medianfilter_rates;
can be marked `static`

2021-08-15 20:02 UTC, OpenUAS commented on sw/airborne/subsystems/imu/imu_mpu6000.c
> +struct MedianFilter3Int medianfilter_rates;
Thanks, will make changes ASAP

2021-08-19 16:50 UTC, gautierhattenberger approved these changes

2021-08-24 14:43 UTC, merged