Setteable MIN_COUSE_SPEED in ahrs_float_dcm
paparazzi/paparazzi pull request #2794
Opened 2021-11-05 15:54 UTC by noether

We are preparing a rover firmware, and we have found it convenient to set this number to a lower value when we use the AHRS_float_dcm.

We leave as default the original hardcoded one.

2021-11-05 22:12 UTC, gautierhattenberger requested changes

2021-11-05 22:12 UTC, gautierhattenberger commented on sw/airborne/subsystems/ahrs/ahrs_float_dcm.c
> +    if (gps_s->gspeed >= MIN_COURSE_SPEED) { //got a 3d fix and ground speed is more than MIN_COURSE_SPEED/100 m/s
I suggest a name like `AHRS_MIN_COURSE_SPEED` or `FLOAT_DCM_MIN_COURSE_SPEED` to make it clear in airframe file that it is related to ahrs filter.
Also, it is probably nicer to have standard units (so m/s): `gps_s->gspeed >= 100 * XXX_MIN_COURSE_SPEED`.

2021-11-06 09:45 UTC, noether commented
yeah, done.

2021-11-06 14:36 UTC, noether commented
Mm I do not know why Semaphore complains.

2021-11-06 19:41 UTC, gautierhattenberger approved these changes

2021-11-06 19:41 UTC, merged