addition to system identification modules
paparazzi/paparazzi pull request #2810
Opened 2021-12-14 00:50 UTC by Rollervi97

Fixed issue on chirp input (integration of chirp signal when noise was not present). Modification of chirp input telemetry message structure (now it includes also the current chirp input value). Addition of two new system identification input signal: doublet and wave.

2021-12-14 08:43 UTC, gautierhattenberger requested changes

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_chirp.c
> +#include "subsystems/datalink/telemetry.h"
there is no subsystems folder anymore on master branch

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_chirp.c
> +// #ifndef CHIRP_EXPONENTIAL
remove if not used anymore

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_doublet.c
> +#include "subsystems/datalink/telemetry.h"
change path to `modules`

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_doublet.h
> +// Created by ASUS on 06/12/2021.
please use correct header

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_wave.c
> +#include "subsystems/datalink/telemetry.h"
change path to `modules`

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_wave.h
> +// Created by ASUS on 07/12/2021.
please use correct header

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_chirp.c
> +#include "stdio.h"
I think it can be removed if it was for debug only

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/pprz_wave.h
> +// Created by ASUS on 08/12/2021.
please use correct header

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/pprz_doublet.h
> +// Created by ASUS on 06/12/2021.
please use correct header and add a new line at end of file

2021-12-14 08:43 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/pprz_doublet.c
> +}
add a new line at end of file

2022-01-03 09:27 UTC, gautierhattenberger commented
@Rollervi97 it is almost ready to merge, you still need to update the modules path that have changed in latest master branch

2022-01-03 09:29 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_chirp.c
> +#include "subsystems/datalink/telemetry.h"
```suggestion
#include "modules/datalink/telemetry.h"
```

2022-01-03 09:29 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_doublet.c
> +#include "subsystems/datalink/telemetry.h"
```suggestion
#include "modules/datalink/telemetry.h"
```

2022-01-03 09:30 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_wave.c
> +#include "subsystems/datalink/telemetry.h"
```suggestion
#include "modules/datalink/telemetry.h"
```

2022-01-03 09:31 UTC, gautierhattenberger requested changes

2022-01-03 09:31 UTC, gautierhattenberger commented on sw/airborne/modules/system_identification/sys_id_wave.h
> +#endif // SYS_ID_WAVE_H
This should be a the end of the header

2022-01-18 09:52 UTC, gautierhattenberger commented
@Rollervi97 update ?

2022-01-20 18:07 UTC, Rollervi97 commented
Sorry for the late reply, in this third push there should be all the modification requested.

2022-01-20 21:55 UTC, gautierhattenberger approved these changes

2022-01-20 21:56 UTC, merged