[doc] documentation for the general architecture
paparazzi/paparazzi pull request #2869
Opened 2022-04-21 17:07 UTC by gautierhattenberger

2022-04-22 12:45 UTC, Fabien-B requested changes

2022-04-22 12:45 UTC, Fabien-B commented on doc/sphinx/source/developer_guide/system_overview.rst
> +The Gound Control Station (GCS) constits of multiples programs, communicating with each other by the software bus `Ivy <https://www.eei.cena.fr/products/ivy/>`_, as seen on the general architecture d
```suggestion
The Ground Control Station (GCS) consists of multiples programs, communicating with each other by the software bus `Ivy <https://www.eei.cena.fr/products/ivy/>`_, as seen on the general architecture diagram above.
```
and may replace the Ivy link for https://ivybus.gitlab.io/

2022-04-22 12:45 UTC, Fabien-B commented on doc/sphinx/source/developer_guide/system_overview.rst
> +The ground segment useually runs on a single laptop, but thanks to its distributed nature, it is also possible to split the tools on different computers connected to the same network or VPN.
```suggestion
The ground segment usually runs on a single laptop, but thanks to its distributed nature, it is also possible to split the tools on different computers connected to the same network or VPN.
```

2022-04-22 12:45 UTC, Fabien-B commented on doc/sphinx/source/developer_guide/system_overview.rst
> +  - Some other services are present, including the communication services allow to send and receive messages from the ground, from an other aircraft
```suggestion
  - Some other services are present, including the communication services that allow to send and receive messages from the ground, from an other aircraft
```

2022-04-22 12:45 UTC, Fabien-B commented on doc/sphinx/source/developer_guide/system_overview.rst
> +The picture below explain the temporal sequence of the autopilot. Each module is declared with a *task* (or nothing for default group) that is called in a predefined order.
Not very clear, maybe that ?
```suggestion
The picture below explain the temporal sequence of the autopilot. Modules are grouped in *tasks* (or nothing for default group) that are called in a predefined order.
```

2022-04-23 08:29 UTC, fvantienen commented on doc/sphinx/source/developer_guide/system_overview.rst
> +The Ground Control Station (GCS) consits of multiples programs, communicating with each other by the software bus `Ivy <https://www.eei.cena.fr/products/ivy/>`_ (see the `documentation <https://ivybu
consits -> consists

2022-04-25 07:23 UTC, Fabien-B approved these changes

2022-04-25 07:23 UTC, merged