Function settings
paparazzi/paparazzi pull request #2880
Opened 2022-05-17 09:20 UTC by fvantienen

Add function only settigs

2022-05-17 09:25 UTC, fvantienen commented
This has a merge conflict with the renaming of `mcu_periph_energy_save` to `mcu_energy_save` with #2859. Preferably this would be merged first, then I will rebase the other PR.

2022-05-18 21:28 UTC, gautierhattenberger requested changes

2022-05-18 21:28 UTC, gautierhattenberger commented on conf/settings/fixedwing_basic.xml
> +    <dl_settings NAME="system">
I suggest `mcu` name, there are already too many `system` tab in settings

2022-05-18 21:28 UTC, gautierhattenberger commented on sw/airborne/arch/chibios/mcu_arch.c
>  #endif
a closing parenthesis is missing

2022-05-18 21:28 UTC, gautierhattenberger commented on sw/airborne/modules/boards/power_switch.c
> +}
new line at end of file is missing, same for header

2022-05-19 12:06 UTC, fvantienen commented
Should be ok to merge now

2022-05-19 21:52 UTC, gautierhattenberger approved these changes

2022-05-19 21:53 UTC, merged