Added driver for QMC5883L Magnetometer
paparazzi/paparazzi pull request #2953
Opened 2022-11-16 21:21 UTC by OpenUAS

Added a driver for the QMC5883L Magnetometer, tested on Baremetal Lisa MXS and Chibios Lisa MXS

![working_qmc5883l_pprz](https://user-images.githubusercontent.com/483944/202296879-bd537c38-0368-4d59-a569-03e97ad16a75.jpg)

2022-11-17 20:56 UTC, gautierhattenberger requested changes

2022-11-17 20:56 UTC, gautierhattenberger commented on sw/airborne/modules/sensors/mag_qmc5883l.c
> +#include "modules/sensors/mag_rm3100.h"
wrong include

2022-11-17 20:56 UTC, gautierhattenberger commented on conf/modules/mag_qmc5883l.xml
> +    <configure name="MAG_QMC5883L_PERIODIC_FREQUENCY" default="60"/>
I would not recommend a frequency of 60Hz by default. I don't know the specs of this sensor, but if possible it is better to have periodic functions as divisors of the main frequency which is by default 500 Hz (or sometimes 512) for rotorcraft, which is where this sensor will be mostly used I guess. So 50 Hz is maybe a better choice.

2022-11-28 11:27 UTC, OpenUAS commented
Changed, a new review appreciated, with PR merge honoring would be best :)

2022-11-28 21:09 UTC, merged