INDI hybrid updates
paparazzi/paparazzi pull request #2954
Opened 2022-11-23 18:15 UTC by EwoudSmeur

We made some code for our Nederdrone project. I'm breaking it down into manageable commits, this one contains:

- Two interpolation segments during transition
- Quadratic lift effectiveness with airspeed
- Velocity setpoint input possible from module via ABI message

Unfortunately I couldn't keep the original commits as there were 150, it was way too much hassle to do pick out the changes without squashing...

2022-11-23 20:31 UTC, gautierhattenberger commented
compilation is failing when `GUIDANCE_INDI_LIFTD_ASQ` is not defined I think. And you have a conflict with the previous pull request.
It seems like what you are doing is to control the speed while flying in FP navigation ? Or something close. The control inputs for indi (and especially for hybrid) are really a mess now I think... I okay to merge something like this as a temporary solution, but we should make something clean and consistent at someday.

2022-11-25 17:33 UTC, EwoudSmeur commented
You're right, forgot to add the airframe file changes. I skipped the Nederdrone ones as they have many more changes, would be easier to do that in one go I believe. There is now also a default.

Regarding the inputs/setpoint/ref, you're right unfortunately... Somehow different sources of a position/velocity/attitude reference (NAV, modules, predefined 4D trajectories, etc.) need to be chosen/prioritized/combined.

2022-11-28 21:13 UTC, gautierhattenberger requested changes

2022-11-28 21:13 UTC, gautierhattenberger commented on sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
> +#ifndef
```suggestion
#ifndef GUIDANCE_INDI_LIFTD_ASQ
```

2022-11-30 10:03 UTC, gautierhattenberger commented on sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
>  #define GUIDANCE_INDI_MAX_PITCH 25
there is a `#endif` missing here

2022-12-02 17:08 UTC, EwoudSmeur commented
Sorry not sure how that happened! Fixed, compiles and works in simulation 👌

2022-12-02 20:58 UTC, gautierhattenberger approved these changes

2022-12-02 20:58 UTC, merged