[conf] Small fixes TU Delft
paparazzi/paparazzi pull request #2965
Opened 2023-01-19 08:44 UTC by fvantienen

2023-01-19 09:40 UTC, gautierhattenberger commented
You have reverted some changes that were "fixing" some errors:
- the replacement of `->` by `@DEREF` in the flight plans
- the `test` node in the nerderdrone control module that is not complete and was removed as you are the only user of this
- some commented codes in `target_pos.c` that were previously removed

2023-01-19 15:03 UTC, fvantienen commented
Sorry ,some were to be changed back but some weren't. Don't know why but the `@DEREF` doesn't work so that one had to be reverted.

2023-01-19 22:28 UTC, gautierhattenberger commented
It seems that the call and call_once functions are not parsed to replace the statements like DEREF. It is is just a direct copy of the code in the final flight plan. I'm not sure if it is a real choice or just something that we have forgotten.

2023-01-25 12:55 UTC, gautierhattenberger requested changes

2023-01-25 12:55 UTC, gautierhattenberger commented on conf/modules/eff_scheduling_nederdrone.xml
> +    <test/>
```suggestion
```

2023-01-25 12:55 UTC, gautierhattenberger commented on sw/airborne/modules/ctrl/target_pos.c
> +/* Get the Relative postion from the RTK */
remove again commented parts ?

2023-02-03 10:01 UTC, gautierhattenberger commented on sw/airborne/modules/ctrl/target_pos.c
> +
```suggestion
```

2023-02-03 10:02 UTC, gautierhattenberger commented on sw/airborne/modules/ctrl/target_pos.c
> +
```suggestion
```

2023-02-03 10:24 UTC, gautierhattenberger approved these changes

2023-02-03 10:25 UTC, merged