[INS_EXT_POSE] Kalman Filter based on external attitude measurements
paparazzi/paparazzi pull request #2993
Opened 2023-02-13 11:04 UTC by dewagter

Some projects (e.g. system identification) require precise attitude from external sources. This filter merges IMU with external attitude from the EXTERNAL_POSE message.

2023-02-13 12:56 UTC, gautierhattenberger requested changes

2023-02-13 12:56 UTC, gautierhattenberger commented on conf/modules/ins_ext_pose.xml
> +    extended kalman filter made by robin.
Batman might be frustrated not to cited here. Any additional link or info about this filter or this particular implementation ?

2023-02-13 12:56 UTC, gautierhattenberger commented on sw/airborne/modules/ins/ins_ext_pose.c
> +	/* Inputs */
run indentation script

2023-02-13 12:56 UTC, gautierhattenberger commented on sw/airborne/modules/loggers/logger_file.c
> +#endif
these headers should be included with the `generated/modules.h`

2023-02-13 12:56 UTC, gautierhattenberger commented on sw/airborne/modules/ins/ins_ext_pose.c
> +static inline void ekf_step(const float U[EKF_NUM_INPUTS], const float Z[EKF_NUM_OUTPUTS], const float dt)
would it be possible to make a generic library like https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/filters/linear_kalman_filter.h ?

2023-02-13 14:37 UTC, dewagter commented on sw/airborne/modules/ins/ins_ext_pose.c
> +	/* Inputs */
done

2023-02-15 08:55 UTC, gautierhattenberger commented on sw/airborne/modules/ins/ins_ext_pose.c
> +static inline void ekf_step(const float U[EKF_NUM_INPUTS], const float Z[EKF_NUM_OUTPUTS], const float dt)
Of course it means that you would have to pass functions for the model and the jacobian, but that is for an other day

2023-02-15 08:56 UTC, gautierhattenberger approved these changes

2023-02-15 08:57 UTC, merged