Feetch servo
paparazzi/paparazzi pull request #3048
Opened 2023-08-01 18:41 UTC by Fabien-B

This is a driver for the STS3032 servomotor.
It is not complete yet, but it has the main functionalities.

2023-08-01 19:43 UTC, gautierhattenberger requested changes
Looks fine. Only minor changes.

2023-08-01 19:43 UTC, gautierhattenberger commented on conf/modules/actuators_sts3032.xml
> +    <depends>uart</depends>
Add `actuators` to dependencies ?
Add `<provides>actuators</depends>` ?

2023-08-01 19:43 UTC, gautierhattenberger commented on sw/airborne/modules/actuators/actuators_sts3032.c
> +  sts.periph = &(STS3032_DEV);
apply indentation script

2023-08-02 08:29 UTC, Fabien-B commented
changes done

2023-08-02 12:26 UTC, gautierhattenberger approved these changes

2023-08-02 12:27 UTC, merged