[modules] Fix follow me
paparazzi/paparazzi pull request #3055
Opened 2023-08-30 16:18 UTC by fvantienen

This removes the possibilities of NaN's and adds the option to move multiples waypoints periodically with the follow_me module. An example flight plan will follow

2023-08-30 21:30 UTC, gautierhattenberger requested changes
just a few minor comments

2023-08-30 21:30 UTC, gautierhattenberger commented on sw/airborne/modules/ctrl/follow_me.c
> +#define FOLLOW_ME_HEIGHT 60
Some default values are not consistent with the comments

2023-09-06 10:14 UTC, dewagter approved these changes
Important fix and nice new features. LGTM

2023-09-06 19:52 UTC, merged

2023-09-12 17:23 UTC, fvantienen commented on sw/airborne/modules/ctrl/follow_me.c
> +    wp_new_enu.y = (-(wp_new_enu.y - cur_targetpos.y) * sin_heading) + ((wp_new_enu.y - cur_targetpos.y) * cos_heading) + cur_targetpos.y;
There is something wrong here with the x and y values