Moving target filter
paparazzi/paparazzi pull request #3067
Opened 2023-09-09 08:25 UTC by dewagter

- high filter values make the filter unstable

2023-09-09 08:39 UTC, EwoudSmeur commented
This should be investigated. Perhaps a first order filter could work better with very low cutoff frequency

2023-09-12 16:31 UTC, fvantienen requested changes

2023-09-12 16:31 UTC, fvantienen commented on sw/airborne/modules/ctrl/approach_moving_target.c
> +  float sample_time = 1.0 / PERIODIC_FREQUENCY;
PERIODIC_FREQUENCY is wrong here, this should be the frequency of the `follow_diagonal_approach` (which is 100Hz) you can get that define out of the generated code.

2023-09-12 16:31 UTC, fvantienen commented on sw/airborne/modules/ctrl/approach_moving_target.c
> +float cutoff_freq_filters_hz = 0.5; // Hz
Maybe add a define for setting the default value

2023-09-12 16:31 UTC, fvantienen commented
> tigated. Perhaps a first order filter could work better with very low cutoff

See my comments, you were filtering with a define which said 500Hz but it was actually running at 100Hz

2023-09-15 09:22 UTC, dewagter reviewed
All requests implemented.

2023-09-15 11:33 UTC, fvantienen approved these changes

2023-09-15 19:51 UTC, merged