[nav] use a low speed for goto with hybrid
paparazzi/paparazzi pull request #3148
Opened 2023-10-26 14:16 UTC by gautierhattenberger

@dewagter @EwoudSmeur @fvantienen This is a proposal to use different speeds for `goto` and `route` to prevent unnecessary transition to forward flight when just going to a waypoint. In most flight plan, the goto is used for small displacement, while using a route is more suitable for longer trajectories where forward flight is useful.
The `force_forward` is still possible.

2023-11-02 10:40 UTC, EwoudSmeur commented
I am not in favor of making this the default behavior. Like you say, if the goto is used only for a small displacement, depending on the position gain the drone will not go to forward flight. If the distance is larger, I see no reason to limit the commanded ground speed. Note that if there is wind, the drone may even be in forward flight regardless.
The other changes seem fine to me!

2023-11-02 10:42 UTC, EwoudSmeur requested changes

2023-11-02 10:42 UTC, EwoudSmeur commented on sw/airborne/modules/nav/nav_rotorcraft_hybrid.c
>        // MAX_BANK / 2 gives some margins for the turns
```suggestion
      // MAX_BANK * 0.8 gives some margins for the turns
```

2023-11-02 10:42 UTC, EwoudSmeur commented on sw/airborne/modules/nav/nav_rotorcraft_hybrid.c
> +#define GUIDANCE_INDI_HOVER_SPEED 5.f
```suggestion
#define GUIDANCE_INDI_HOVER_SPEED NAV_MAX_SPEED
```
I'm not fully convinced with the name 'hover_speed'.

2023-11-03 20:27 UTC, gautierhattenberger commented
@EwoudSmeur I changed the name, made the max speed the default as you suggested, and add some doc

2023-11-04 12:17 UTC, dewagter approved these changes
I'm OK with this extra option. The default when ```GUIDANCE_INDI_GOTO_SPEED``` is not defined remains the same so that is great.

2023-11-06 08:59 UTC, EwoudSmeur approved these changes
Great, thanks!

2023-11-06 09:00 UTC, merged