Wing rotation controller -> state
paparazzi/paparazzi pull request #3177
Opened 2023-11-15 09:13 UTC by dewagter

- same code for 3B and 25
 - removed wing_rotation_controller_servo

2023-11-23 15:33 UTC, gautierhattenberger requested changes

2023-11-23 15:33 UTC, gautierhattenberger commented on conf/modules/wing_rotation_controller_can.xml
> +    <periodic fun="wing_rotation_event()"/>
maybe not the most appropriate name (event/periodic)

2023-11-23 15:33 UTC, gautierhattenberger commented on conf/modules/wing_rotation_controller_can.xml
> +  <header>
add dependency on can modules ?

2023-11-23 15:33 UTC, gautierhattenberger commented on sw/airborne/modules/rot_wing_drone/wing_rotation_controller_can.c
> +float pprz_angle_step = 9600. / 45.; // CMD per degree
is this a real constant or should it be configurable ?

2023-12-13 10:29 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/wing_rotation_adc_sensor.c
> +#ifndef ADC_CHANNEL_WING_ROTATION_CONTROLLER_POSITION
ok

2023-12-13 10:32 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/wing_rotation_adc_sensor.c
> +}
ok

2023-12-13 10:32 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/wing_rotation_adc_sensor.c
> +  AbiSendMsgACT_FEEDBACK(ACT_FEEDBACK_UAVCAN_ID, &feedback, 1);
Module will be removed as soon as 3B is converted. Will not fix this.

2023-12-13 10:33 UTC, dewagter commented on conf/modules/wing_rotation_adc_sensor.xml
> +  </doc>
added docs for the only configure

2023-12-13 10:35 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/wing_rotation_adc_sensor.c
> + * Module to read skew angle from adc sensor
Will be removed as soon as 3B is converted to CAN wing control.

2023-12-13 10:35 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/wing_rotation_adc_sensor.c
> +  feedback.idx =  SERVO_ROTATION_MECH;
OK

2023-12-13 10:36 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/rotwing_state.c
> +    feedback.idx =  SERVO_ROTATION_MECH;
changed!

2023-12-13 10:37 UTC, dewagter commented on conf/modules/rotwing_state.xml
>    </header>
ok

2023-12-13 10:56 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/rotwing_state.c
> +#if ROTWING_STATE_PD_WING_ROTATION
Made it static local.

2023-12-13 10:57 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/rotwing_state.c
> +#if ROTWING_STATE_PD_WING_ROTATION
Renamed the PD_WING_ROTATION to USE_ROTATION_REF_MODEL ... this is not a PD controller but a reference generator.

2023-12-13 10:57 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/rotwing_state.c
> +  rotwing_state_skewing.servo_pprz_cmd = rotwing_state_skew_p_cmd;
renamed

2023-12-13 11:05 UTC, dewagter commented on sw/airborne/modules/rot_wing_drone/rotwing_state.c
> +    actuators_pprz[INDI_NUM_ACT] = (rotwing_state_skewing.servo_pprz_cmd + MAX_PPRZ) / 2.; // Scale to simulation command
solved

2023-12-13 12:51 UTC, dewagter commented on sw/airborne/modules/ctrl/eff_scheduling_rot_wing.c
>  #error ctrl_eff_sched_rot_wing requires a servo named ROTATION_MECH
```suggestion
#error ctrl_eff_sched_rot_wing requires a servo named ROTATION_MECH_IDX
```

2023-12-13 13:23 UTC, merged