Jpo2023-Chimera-WS2812
paparazzi/paparazzi pull request #3188
Opened 2023-11-27 13:52 UTC by amtcvx

2023-11-27 20:38 UTC, gautierhattenberger requested changes

2023-11-27 20:38 UTC, gautierhattenberger commented on sw/airborne/boards/chimera/chibios/v1.0/mcuconf.h
> +#ifndef STM32_PWM_USE_TIM8
Something is wrong or missing

2023-11-28 08:12 UTC, amtcvx commented on sw/airborne/boards/chimera/chibios/v1.0/mcuconf.h
> +#ifndef STM32_PWM_USE_TIM8
Ok adding endif after define

2023-11-28 08:19 UTC, gautierhattenberger approved these changes

2023-11-28 08:19 UTC, merged