Rename ground detect
paparazzi/paparazzi pull request #3365
Opened 2024-09-23 14:45 UTC by dewagter

2024-09-26 09:45 UTC, dewagter commented on conf/modules/ground_detect.xml
> +  <periodic fun="ground_detect_filter_accel()" freq="500"/>
```suggestion
  <periodic fun="ground_detect_filter_accel()"/>
```
Agreed!

2024-09-28 12:08 UTC, gautierhattenberger submitted a review, later dismissed

2024-09-28 12:08 UTC, gautierhattenberger commented on conf/airframes/tudelft/rotwing5.xml
> +    <section name="CTRL_EFF_SHED" prefix="ROT_WING_EFF_SCHED_">
Are you sure about the name ? I think you changed them all to `ROTWING_`

2024-09-28 12:08 UTC, gautierhattenberger commented on conf/airframes/tudelft/rotwing_v3b.xml
> +    <section name="CTRL_EFF_SHED" prefix="ROT_WING_EFF_SCHED_">
same here

2024-09-28 21:29 UTC, gautierhattenberger requested changes

2024-09-28 21:29 UTC, gautierhattenberger commented on conf/modules/ground_detect.xml
> +      <define name="PERIODIC_TELEMETRY" value="0"/>
`PERIODIC_TELEMETRY` is enabled for tests, so adding it here makes a `redefined` warning and doesn't disable it. Instead add something like:
```
      <define name="DOWNLINK_TRANSPORT" value="pprz_tp"/>
      <define name="DOWNLINK_DEVICE" value="uart0"/>
      <define name="USE_UART0"/>
```

2024-09-28 21:29 UTC, gautierhattenberger commented on sw/airborne/modules/nav/ground_detect.c
> +  payload[5] = agl_dist_value_filtered;
These lines should be protected with `#if USE_GROUND_DETECT_AGL_DIST`

2024-10-01 10:48 UTC, gautierhattenberger approved these changes

2024-10-01 10:56 UTC, merged