Merge RotWing State Machine
paparazzi/paparazzi pull request #3397
Opened 2024-10-15 13:08 UTC by tmldeponti

I have modified the new state machine by @fvantienen to be independent of guidance indi hybrid. It is then possible to also use this state machine with the oneloop controller. This allows us to merge the two state machines and have only one common shared one.

2024-10-16 05:32 UTC, dewagter commented
I agree to move some functions to maximize reusability, but can you please fix the compile issue. (```make tudelft``` and  ```make tests```)

2024-10-16 09:12 UTC, tmldeponti commented
> I agree to move some functions to maximize reusability of modules, but can you please fix the compile issue. (`make tudelft` and `make tests`)

Yes I am on it! :)

2024-10-18 13:58 UTC, tmldeponti commented
> I agree to move some functions to maximize reusability of modules, but can you please fix the compile issue. (`make tudelft` and `make tests`)

I fixed all errors in the test modules. As for test tudelft, the airframes with the oneloop controller will be fixed in the next PR I will open about the oneloop.

2024-10-29 09:56 UTC, fvantienen requested changes

2024-10-29 09:56 UTC, fvantienen commented on conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack_ext_pose.xml
> +        <define name="ROTWING_FW_SKEW_ANGLE"    value="85"/>
That define does not work

2024-10-29 09:56 UTC, fvantienen commented on conf/airframes/tudelft/rotwing_v3c_oneloop_simulation.xml
> +        <define name="ROTWING_FW_SKEW_ANGLE"    value="85"/>
Same here

2024-10-29 09:56 UTC, fvantienen commented on conf/airframes/tudelft/rotwing_v3g_oneloop_optitrack_ext_pose.xml
> +        <define name="ROTWING_FW_SKEW_ANGLE"    value="85"/>
Same

2024-10-30 15:46 UTC, fvantienen approved these changes

2024-10-30 15:47 UTC, merged