Driver for Goermicro SPA06-003
paparazzi/paparazzi pull request #3412
Opened 2024-11-27 12:52 UTC by FlorianSan

Driver for Goermicro SPA06-003 barometer.
Only test in I2C with a speedybee AIO F405

2024-11-27 14:27 UTC, gautierhattenberger requested changes

2025-03-31 13:52 UTC, gautierhattenberger requested changes

2025-08-15 13:53 UTC, OpenUAS commented
@FlorianSan Would it be possible to implement the changes? If not I'll redo the PR in a bit, Do have the hardware to testfly it also.

2025-08-28 08:33 UTC, gautierhattenberger commented
@FlorianSan has finished his PhD with us and he's no longer working here. @OpenUAS If you think you can finish this PR, go ahead. Otherwise it will go to our todo list, but not with the highest priority...

2026-07-18 21:37 UTC, OpenUAS commented
Since PR #3676 replaces this driver, no need for this PR anymore.

2026-07-18 21:37 UTC, closed without merging